### ISSUE TITLE
Set custom maxY

### ISSUE THREAD

**Issue by margarita-v** [patrykandpatryk/vico#100]
For example, for a chart:
<img width="495" alt="Снимок экрана 2022-07-02 в 21 05 15" src="https://user-images.githubusercontent.com/22121595/177011675-3c570c82-90e3-481e-be34-766ac79f94dd.png">

It's impossible to show ThresholdLine for a value which is higher than other values on Y axis, thresholdValue must be in between. Is there any workaround?

**Comment by patrykmichalik** [comment]
Hello! You can achieve this by specifying a custom `maxY` value. In the `compose` module, `columnChart` and `lineChart` have `maxY` parameters: `columnChart(maxY = 10f)`. In the view system, you can set a custom `maxY` value as follows: `chartView.chart?.maxY = 10f` (where `chartView` is a reference to your `ChartView` instance).

**Comment by margarita-v** [comment]
Thank you, it works!

**Comment by patrykmichalik** [comment]
Sure thing.
