### ISSUE TITLE
Same start point for a chart and a threshold

### ISSUE THREAD

**Issue by margarita-v** [patrykandpatryk/vico#101]
The chart always starts from the middle point of x value, though a threshold starts from the beginning of axes. Is there any way to start the chart from the same starting point?
![Screenshot_20220702_210815](https://user-images.githubusercontent.com/22121595/177011843-44ab5411-be4e-4419-8c91-81850e32e026.jpg)

**Comment by patrykmichalik** [comment]
Hello! I’m afraid this isn’t possible as of now, but we’ll be looking into adding such functionality. Thanks for the suggestion!

**Comment by patrykmichalik** [comment]
Hello again! [Vico 1.4.0](https://github.com/patrykandpatryk/vico/releases/tag/v1.4.0) is now rolling out, and it includes the feature in question. The update should be available within 30 minutes.
