### ISSUE TITLE
Clamping number of displayed values

### ISSUE THREAD

**Issue by rainboy93** [patrykandpatryk/vico#103]
Hi, 
Thank for your hard work.

![image](https://user-images.githubusercontent.com/12291646/178541145-804353e1-805d-42c5-b54d-32fb5d8b35ed.png)

Currently, If number of values on chart is small then we will have many empty space on the right side.
How to auto clamping the chart with the values spread and have scale disabled if we scale two small.

**Comment by patrykmichalik** [comment]
Hello! As of Vico 1.2.0, charts are automatically scaled up in such instances, so the issue in question is no longer present.
