### ISSUE TITLE
Bottom Axis as Date

### ISSUE THREAD

**Issue by galharth** [patrykandpatryk/vico#105]
I want to create a graph like this (with options to change range to per day, week, month, or year):
![Screen Shot on 2022-07-14 at 11-03-09](https://user-images.githubusercontent.com/564274/178933145-e286efa7-9ea7-464b-ae4d-55e012fcc128.png)

The problems I get with the current vico version: 
1. Can pass only float entries
2.  When I pass float entries, vico automatically fills the gaps between the entries I entered and sorts them by size, it wants to enter entries like [29 30 01 06 12] and see them on the graph in this order without filling numbers like [01 02 03 .. 30].

Is it possible to add this stuff in future versions?

Thanks :)

**Comment by patrykmichalik** [comment]
Hello! The current version of Vico contains some limitations that would make it relatively time-consuming to implement such a chart. The next update will remove said limitations. Once itʼs available, Iʼll post a comment here and show you how the chart in question could be created. Thanks for the suggestions!

**Comment by patrykmichalik** [comment]
Hello! In Vico 1.3.0, a solution along these lines could be used:

```kt
class Entry(
    val localDate: LocalDate,
    override val x: Float,
    override val y: Float,
) : ChartEntry {

    override fun withY(y: Float) = Entry(
        localDate = this.localDate,
        x = this.x,
        y = y,
    )
}

val chartEntryModelProducer = listOf(
    "2022-07-14" to 1.3f,
    "2022-07-15" to 2.5f,
    "2022-07-17" to 2.5f,
    "2022-08-01" to 3f,
).mapIndexed { index, (dateString, y) ->

    Entry(
        localDate = LocalDate.parse(dateString),
        x = index.toFloat(),
        y = y,
    )
}.let { entryCollection -> ChartEntryModelProducer(entryCollection) }

val bottomAxis = bottomAxis(
    valueFormatter = { value, chartValues ->
        (chartValues.chartEntryModel.entries[0].getOrNull(value.toInt()) as Entry?)
            ?.localDate
            ?.dayOfMonth
            ?.toString()
            .orEmpty()
    },
)

Chart(
    modifier = modifier,
    chart = columnChart(),
    chartModelProducer = chartEntryModelProducer,
    startAxis = startAxis(),
    bottomAxis = bottomAxis,
    marker = marker(),
)
```

![image](https://user-images.githubusercontent.com/56888459/181445459-920690cd-e00a-4ade-9a9f-569b969e9e55.png)
