### ISSUE TITLE
Allow different bezier curve types on LineSpec

### ISSUE THREAD

**Issue by carloshs94** [patrykandpatryk/vico#113]
Is it possible to achieve this linecharts with vico?

Custom:
<img width="291" alt="customchart" src="https://user-images.githubusercontent.com/14913578/183069059-f8baac53-0811-49aa-a84f-d0168582aedf.PNG">
I'm not sure if this custom chart is using quadratic bezier curves.

Vico: 
<img width="309" alt="vicochart" src="https://user-images.githubusercontent.com/14913578/183069070-42448178-a3d4-43e5-a954-dddc38d0f6bc.PNG">
i been playing with the cubic strength but i guess the cubic bezier curve doesnt allow to have the smoothness of the custom one

Vico cubic strenght 0.2:
<img width="307" alt="vicochartcubicstrenght0 2" src="https://user-images.githubusercontent.com/14913578/183070150-db3fba81-9c84-48bb-8caa-6a4a99a50fc3.PNG">

**Comment by patrykmichalik** [comment]
Hello! Thank you for the suggestion. The next Vico update will introduce the ability to further customize the shape of a line chart’s line or lines. It’ll be possible to entirely override the point connection logic and use any kind of curve.

**Comment by patrykmichalik** [comment]
Hello again! [Vico 1.4.0](https://github.com/patrykandpatryk/vico/releases/tag/v1.4.0) is now rolling out, and it includes the feature in question. The `lineSpec` composable function and the `LineChart.LineSpec` constructor both now have a `pointConnector` parameter. You can use this to provide a custom `PointConnector` implementation. The update should be available within 30 minutes.
