### ISSUE TITLE
Crash on specific range for random entries generation while drawing a label

### ISSUE THREAD

**Issue by margarita-v** [patrykandpatryk/vico#115]
Hard to reproduce.
For example, we have a following random entries generation config:
```
private val generator = RandomEntriesGenerator(
        xRange = IntProgression.fromClosedRange(0, 24, 2),
        yRange = 0..1000,
    )
```
The chart has a label, the code is almost the same which is given in the sample, only UI settings are different.
For this chart:
<img width="225" alt="Снимок экрана 2022-08-07 в 17 00 02" src="https://user-images.githubusercontent.com/22121595/183294593-05b44c43-0368-42ba-89a2-b55fc461b8bc.png">
When we tap on the lowest point to see the label, a crash is happening:
```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 513.1875 is less than minimum 530.1875.
        at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1263)
        at com.patrykandpatryk.vico.core.component.shape.cornered.MarkerCorneredShape.drawShape(MarkerCorneredShape.kt:86)
        at com.patrykandpatryk.vico.core.component.shape.ShapeComponent.draw$lambda-3$drawShape(ShapeComponent.kt:99)
        at com.patrykandpatryk.vico.core.component.shape.ShapeComponent.draw(ShapeComponent.kt:110)
        at com.patrykandpatryk.vico.core.component.text.TextComponent.drawText(TextComponent.kt:200)
        at com.patrykandpatryk.vico.core.component.text.TextComponent.drawText$default(TextComponent.kt:133)
        at com.patrykandpatryk.vico.core.component.marker.MarkerComponent.drawLabel(MarkerComponent.kt:104)
        at com.patrykandpatryk.vico.core.component.marker.MarkerComponent.draw(MarkerComponent.kt:89)
```
I've checked multiple times, the lowest point has to be close to zero:
<img width="221" alt="Снимок экрана 2022-08-07 в 17 05 00" src="https://user-images.githubusercontent.com/22121595/183294662-8d9ed95b-7326-4adf-a904-e580cb3e2251.png">
`java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 80.1875 is less than minimum 97.1875.`

Another sample:
<img width="222" alt="Снимок экрана 2022-08-07 в 17 07 20" src="https://user-images.githubusercontent.com/22121595/183294825-029757a4-ce13-492d-95b6-301d6ce9262b.png">
<img width="234" alt="Снимок экрана 2022-08-07 в 17 07 23" src="https://user-images.githubusercontent.com/22121595/183294827-5de6496b-6f00-4cb1-afb5-ab413747660f.png">
Crash on tap on the lowest point:
`    java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 645.1875 is less than minimum 662.1875.
`

No crash when I update the generation this way:
```
private val generator = RandomEntriesGenerator(
        xRange = IntProgression.fromClosedRange(0, 24, 2),
        yRange = 100..1000,
    )
```

**Comment by patrykmichalik** [comment]
Hello! Thanks for the bug report. Unfortunately, I can’t seem to reproduce this. Would you be able to provide a full minimal reproducible example? Cheers!

**Comment by margarita-v** [comment]
I realized that the marker settings affect the crash. Please update in the following sample from repo:
```
// ShowcaseViewModel
private val customStepGenerator = RandomEntriesGenerator(
        xRange = IntProgression.fromClosedRange(rangeStart = 0, rangeEnd = 24, step = 2),
        yRange = 0..100,
    )
// com.patrykandpatryk.vico.sample.util.getMarker
return object : MarkerComponent(
        label = label,
        indicator = indicator,
        guideline = guideline,
    ) {
        init {
            // same
            labelFormatter =
                MarkerLabelFormatter { markedEntries ->
                    markedEntries.firstOrNull()?.entry?.y?.toInt()?.toString().orEmpty()
                } // attention: it causes the crash
        }
```
And now the sample crashes from app start

**Comment by patrykmichalik** [comment]
Thanks! I’ve reproduced the crash and identified the issue. We’ll be looking into it.
