### ISSUE TITLE
Customize or disable chart animation

### ISSUE THREAD

**Issue by margarita-v** [patrykandpatryk/vico#117]
Thanks again for the great library :)
I use it in app with fragments, navigation component, bottom bar, render the chart data in `onViewCreated`. But the chart animation is repeated whenever I enter the tab again though the data should be the same. Is it a way to disable the animation or customize it?

https://user-images.githubusercontent.com/22121595/184478833-33280a0f-bbac-4408-a3fb-86c28840c610.mp4

**Comment by patrykmichalik** [comment]
Hello! We’re glad Vico has been useful to you. The next update will introduce the ability to disable the animation in question. I’ll let you know once the update is available.
