### ISSUE TITLE
Scrolling to a Certain Point at the beginning

### ISSUE THREAD

**Issue by Praveen2106** [patrykandpatryk/vico#132]
Hi, 
I came to know about this library just today. I started playing around with it and I'm very impressed with the number of features offered. 

I believe it will become the top alternative for the MPAndroidChart. 

I just wanted to know whether you can scroll to a certain point at the beginning. Say I want to scroll to the last point so the user will scroll left instead of right. This makes sense when using date & time for X-Axis. 

I've gone through the documentation. But I couldn't find any mention of scrolling to a certain point.

**Comment by patrykmichalik** [comment]
Hello! Cheers for the kind words. This is a feature that we’re working on at the moment. It’ll be added with the next update.

**Comment by Praveen2106** [comment]
That's great to hear! 

Thank you.

**Comment by patrykmichalik** [comment]
[Vico 1.5.0](https://github.com/patrykandpatryk/vico/releases/tag/v1.5.0) is now rolling out, and it includes the feature in question. The update should be available within half an hour.
