### ISSUE TITLE
Custom text for marker label

### ISSUE THREAD

**Issue by permiakover** [patrykandpatryk/vico#133]
Hello, i'd like to set marks on chart with custom text, for example - "A", "B", "C" etc. Is it possible?

**Comment by patrykmichalik** [comment]
Hello! You can use a `MarkerLabelFormatter` for this purpose. `MarkerComponent` has a `labelFormatter` field.

**Comment by BlazeCodeDev** [comment]
Could you provide a sample code on how you would go about that? The formatter only provides basic x and y values as far as I'm concerned. I'm missing an index value or something similar.

**Comment by patrickmichalik** [comment]
Please see [here](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values), @BlazeCodeDev.

**Comment by jalalaghazadeh** [comment]
> Please see [here](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values), @BlazeCodeDev.

Page Not Found :((

**Comment by Gowsky** [comment]
Hello, @jalalaghazadeh. Based on other threads, it looks like you're using Vico 2, so please see [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/value-formatting) and [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/markers).
