### ISSUE TITLE
Setting runInitialAnimation to false has no effect

### ISSUE THREAD

**Issue by Praveen2106** [patrykandpatryk/vico#135]
Hi, 
Setting runInitialAnimation to false still animates the chart during the Composition. 

Are any additional steps required for not showing any animation initially?

**Comment by permiakover** [comment]
https://github.com/patrykandpatryk/vico/issues/131

**Comment by patrykmichalik** [comment]
Hi! Please keep in mind that `runInitialAnimation` affects only the animation displayed when a chart is first created. Please see #131 for information on how to disable all difference animations.
