### ISSUE TITLE
Mix of positive and negative values in Barchart?

### ISSUE THREAD

**Issue by parrotcar00** [patrykandpatryk/vico#138]
Does Vico support a mix of positive and negative integer values in a Barchart? I tried a simple bar chart with a mix of positive and negative y-axis values and the resulting bar chart was strange. Before I try any further, wanted to confirm if this is indeed a supported usecase?

**Comment by Gowsky** [comment]
Hello @parrotcar00,
Unfortunately, it’s not supported yet, but it’s a feature we will implement soon.

**Comment by parrotcar00** [comment]
While I was trying to figure out how to best create a chart to display a collection of positive and negative values, I came across this chart:
![Horizontal bar chart](https://user-images.githubusercontent.com/18076659/52962701-3e9f7e00-339e-11e9-8f34-1b42b684e341.png)

Seems to me if positive and negative values come into play in a bar chart, then horizontal bar charts become easier to read?
Just sharing some food for thought.
Thanks for your work!

**Comment by Gowsky** [comment]
This is a different type of column chart that we didn’t plan to implement yet.
Our goal is to achieve something like below.

![image](https://user-images.githubusercontent.com/14221573/196002531-1e7e8591-8911-4be9-8783-2a8a61e8c6f0.png)

**Comment by parrotcar00** [comment]
I only shared it as something I thought about, maybe good as a future enhancement idea?

Your above solution absolutely works :)

**Comment by patrykmichalik** [comment]
Hello! Vico 1.5.1 is now available, and it introduces the improvement in question.
