### ISSUE TITLE
How to make a scrollable list of charts?

### ISSUE THREAD

**Issue by parrotcar00** [patrykandpatryk/vico#142]
I wanted to have a list of multiple charts, one chart per card and multiple such cards laid out in a vertical list fashion. but when I do this, with a list of say 30 charts, the list doesn't scroll (getting clipped abruptly at card #3 for instance).

Here's a code fragment that I had tried:

```
//Simply prints a list made up of a repeated charts
@Composable
public fun ChartsContainer() {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .fillMaxHeight(0.8f)
            .verticalScroll(rememberScrollState()),
    ) {
        Spacer(modifier = Modifier.height(20.dp))
        repeat(30) {
            ChartCard(count = it)
        }
    }
}

@Composable
public fun ChartCard(count: Int = 0) {
    val listFloatEntry1: List<FloatEntry> =
        listOf(
            FloatEntry(x = 0f, y = 500f),
            FloatEntry(x = 10f, y = 300f),
            FloatEntry(x = 20f, y = 100f),
        )

    val chartEntryModelProducer1: ChartEntryModelProducer = ChartEntryModelProducer()
    chartEntryModelProducer1.setEntries(listFloatEntry1)

    Card(modifier = Modifier.padding(3.dp)) {
        Text("Chart number: $count")
        Chart(
            chart = columnChart(),
            chartModelProducer = chartEntryModelProducer1,
            startAxis = startAxis(title = "Foo", titleComponent = textComponent {}),
            bottomAxis = bottomAxis(
                title = "Baz",
                titleComponent = textComponent {},
                tickPosition = HorizontalAxis.TickPosition.Center(
                    offset = 0,
                    spacing = 5,
                ),
            ),
        )
    }
}


```
Here's what the above looks like:
![Chart list not scrollable](https://i.imgur.com/5Td93wD.jpg)

Notice how it's getting clipped at the third chart and not scrollable.

How do I make a scrollable list of charts?

**Comment by Gowsky** [comment]
Hi @parrotcar00!
Your list is cut-off because of `0.8f` in your `fillMaxHeight` `Modifier`.
The inability to scroll is caused by one of gestures `Modifier`s that are applied by Vico that steal touch events from scrollable `Column`. We'll need to take a look on how to improve that. You can still perform scrolling by starting the scroll in area not taken by charts.

**Comment by parrotcar00** [comment]
If I remove the line .fillMaxHeight(0.8f) altogether, I get a little bit more of the chart but it's still not scrollable.

> You can still perform scrolling by starting the scroll in area not taken by charts.

Can you expand more on this or any example?

**Comment by parrotcar00** [comment]
Got it, I'll try that.
Also, in the meantime, is there any way to disable all gestures in Chart area? I'm trying to think of a workaround?

If the charts are the main item inside a card, it'll be hard to keep the user from expecting to scroll while touching the chart. Maybe I can disable all gestures on Chart?

**Comment by patrykmichalik** [comment]
As a workaround, you could set `isZoomEnabled` to `false`. It looks like the zoom logic is what’s causing vertical swipes to be consumed. I’ve just corrected this bug.

**Comment by parrotcar00** [comment]
> As a workaround, you could set `isZoomEnabled` to `false`. It looks like the zoom logic is what’s causing vertical swipes to be consumed. I’ve just corrected this bug.

Can confirm, setting isZoomEnabled = false on the Chart makes the list scrollable.

**Comment by patrykmichalik** [comment]
Hello! As of Vico 1.5.1, which is now available, charts no longer consume vertical swipes. You should be able to change `isZoomEnabled` back to `true` without any impact to the scrolling behavior.
