### ISSUE TITLE
Allow markerVisibilityChangeListerner to give back which entry from the array that was clicked

### ISSUE THREAD

**Issue by Syrou** [patrykandpatryk/vico#146]
Hi, we are trying to make the marker show a tooltip that contains more data than just the y-value, this could be made outside of vico if
markerVisibilityChangeListener also contained which entry was clicked, could this be added?

**Comment by patrykmichalik** [comment]
Hello! This feature has been added with [version 1.5.2](https://github.com/patrykandpatryk/vico/releases/tag/v1.5.2), which is rolling out now and should be available within half an hour.
