### ISSUE TITLE
Make ColumnChart bottomAxis support multiline labels that are not float and can be centered

### ISSUE THREAD

**Issue by Syrou** [patrykandpatryk/vico#147]
It would be great if the bottomAxis for ColumnChart could be something else than Float and also support multiple line entries
such as: 

5th
April
2002

and make sure all lines are centered horizontally

**Comment by patrykmichalik** [comment]
Hello! [Version 1.5.2](https://github.com/patrykandpatryk/vico/releases/tag/v1.5.2) adds a `textAlign` field to `TextComponent`. As you’ve noted, you can use this and the newline character to achieve the desired result. Regarding your suggestion, could you elaborate on what kind of solution for multi-line text you’d like to see added? When `lineCount` is greater than 1, automatic text wrapping is used.

**Comment by patrykmichalik** [comment]
I’ll be closing this PR due to inactivity, but please feel free to reopen it. Thank you for your suggestions!
