### ISSUE TITLE
Feature request: Fading edges

### ISSUE THREAD

**Issue by mildroid** [patrykandpatryk/vico#153]
Hi.
Well done with the library, it will be very cool if you add some kind of fading edges to end and start of Line Chart.

like this one
![image_processing20210909-2715-ebfuab](https://user-images.githubusercontent.com/54042378/200905187-fd923946-8b12-40f7-bf5b-0ece362e1d47.png)

**Comment by patrykmichalik** [comment]
Hello! Vico 1.6.0, which is now rolling out, adds the feature in question. Thank you for the suggestion!
