### ISSUE TITLE
Custom top value and empty chart data

### ISSUE THREAD

**Issue by harryPowellx** [patrykandpatryk/vico#154]
Hello. First of all I want to thank you for this amazing library.
Currently I have two problems. I want to show a time based chart(minutes per days in a week period)
1. The library generates startAxis values itself. Is there any way to customize it? I want to step every row by 1 hour.
![Screenshot_1668081436](https://user-images.githubusercontent.com/87462520/201084858-fae42ec5-d679-4074-a11b-e03f24af3a33.png)
For example in this case steps should be 1h, 2h and 3h.
note that inputs are per minute.

2. How can I cut the line when entered value is 0? In the above sample the line should stop in Tuesday.

Thank you.

**Comment by harryPowellx** [comment]
Thanks for your passion.
For 2nd problem, I mean Tuesday because the is no data available for Friday, Saturday, and Sunday(the values are 0.0 for these days). I want the final chart to look like this:
![Screenshot_1668103571](https://user-images.githubusercontent.com/87462520/201174805-9e434e62-c47b-4f4f-86c0-a98acd004d54.png)

**Comment by patrykmichalik** [comment]
In that case, I’d suggest not adding entries with a y-axis value of zero to the entry list to begin with. For example, if you have a list of numbers that you map to `ChartEntry` instances, you can use `.filter { it != 0f }` before `map`.

**Comment by harryPowellx** [comment]
Thanks.
