### ISSUE TITLE
Possibility for xAxis elements to be text instead of numbers

### ISSUE THREAD

**Issue by jeluchu** [patrykandpatryk/vico#156]
Maybe this is and I'm not realising it, but the idea would be that instead of numbers appearing in the bottomAxis of the elements (e.g. 0, 1, 2, 3...), text defined in the data model (e.g. Mon, Tues, Wed...) or another type of text that the developer defines in the model could appear, instead of getting the numerical data.

As I said, I don't know if this possibility currently exists, if it does, I would like to know how to apply it.

**Comment by jeluchu** [comment]
I have already figured out how to do this, maybe it would be good to include an example to make it easier to approach from the beginning, I leave it as a suggestion and close the issue, thank you very much for your work!

**Comment by patrykmichalik** [comment]
Hello! I’m glad to hear that you’ve figured out how to achieve the desired result. `AxisValueFormatter`s are described in the wiki (see [here](https://patrykandpatryk.com/vico/wiki/core-topics/chart-axes/#axisvalueformatters) and [here](https://patrykandpatryk.com/vico/wiki/core-topics/custom-data-types)). I’ve just updated one of the sample charts such that the names of the days of the week are displayed along the bottom axis. Thank you for the suggestion!

<img src="https://user-images.githubusercontent.com/56888459/203024132-06de3210-e0f2-468e-b5d3-2facf47a0c1e.png" width="360" />
