### ISSUE TITLE
Bug: Column thickness and spacing changes depending on the data count

### ISSUE THREAD

**Issue by risalfajar** [patrykandpatryk/vico#157]
This is the preview I get from Jetpack Compose, you can see that the more the data displayed, the smaller the column is.

![image](https://user-images.githubusercontent.com/28381124/203094167-35b24c95-2a9d-4653-a036-363eecf4573c.png)

**Expected behavior**
Column thickness and spacing should be consistent regardless of how much data is displayed, if the data is too much to display in the screen, then it should be horizontally scrollable.

Code:
```kotlin
Chart(
    chart = columnChart(
        columns = listOf(
            LineComponent(context.getColor(R.color.primary), 1f, shape = pillShape),
            LineComponent(context.getColor(R.color.secondary), 1f, shape = pillShape),
        ),
        dataLabel = textComponent {
            typeface = Typeface.SANS_SERIF
            textAlign = Paint.Align.CENTER
            color = android.graphics.Color.WHITE
        },
        dataLabelVerticalPosition = VerticalPosition.Bottom,
        spacing = 4.dp,
        innerSpacing = 0.1.dp
    ),
    model = entryModelOf(frequencies, remainingStocks),
    startAxis = startAxis(
        label = axisLabelComponent(typeface = Typeface.SANS_SERIF, textSize = 10.sp, lineCount = 1),
        axis = null,
        tick = null,
        guideline = axisGuidelineComponent(shape = Shapes.rectShape, color = Color.LightGray.copy(alpha = .25f)),
        valueFormatter = DecimalFormatAxisValueFormatter("##")
    ),
    bottomAxis = bottomAxis(
        label = axisLabelComponent(typeface = Typeface.SANS_SERIF, textSize = 10.sp, lineCount = 1),
        guideline = null,
        tick = null,
        axis = null,
        valueFormatter = { value, _ -> labels[value.roundToInt()] }
    ),
)
```

**Comment by risalfajar** [comment]
To add more context, in the app I'm working on, the columns count is dynamic, it isn't fixed like _January-December_ for example. It can be few or many, depending on the data sent by the API. That's why I want to make the column thickness static regardless of columns count.

Yes I'm agreed, I think we need parameter like in point 2.

And if I understand your first point right, shouldn't `thicknessDp` named `minThicknessDp` instead?

**Comment by patrykmichalik** [comment]
I’ll add the parameter in question as soon as possible. Regarding `thicknessDp`, it’s not so much the minimum width as it is the intrinsic width. It’s multiplied by `thicknessScale` in the `draw*` functions of `LineComponent`. The factor can be greater than 1, equal to 1, or smaller than 1. We’ll discuss renaming the parameter to `intrinsicWidth`. Cheers for the context and the suggestion!

**Comment by risalfajar** [comment]
Thanks, that was fast. Hope it can be released soon!

IMO this is the best chart library for Android right now. Keep rocking! 🤓

**Comment by patrykmichalik** [comment]
Thanks for the kind words! We plan on releasing Vico 1.6.0 this week.

**Comment by patrykmichalik** [comment]
Hello! Vico 1.6.0, which is now rolling out, adds the feature in question. Thank you for the suggestion!

**Comment by asker517** [comment]
> Hello! Vico 1.6.0, which is now rolling out, adds the feature in question. Thank you for the suggestion!

@Gowsky is 2.x version has merged this feature?

**Comment by Gowsky** [comment]
Hello, @asker517. Yes, this functionality is available in Vico 2, but the API differs. Please see [here](https://www.patrykandpatrick.com/vico/guide/stable/android/compose/cartesian-charts/cartesian-chart#scroll-and-zoom).

**Comment by marcosalis** [comment]
> Please see [here](https://patrykandpatrick.com/vico/wiki/cartesian-charts/hosts#scroll-and-zoom).

Hello, unfortunately the link is broken, how do we achieve fixed-size columns in Vico 2?
Thank you!

**Comment by Gowsky** [comment]
> Hello, unfortunately the link is broken, how do we achieve fixed-size columns in Vico 2?
> Thank you!

Hello, @marcosalis. I've updated the link in the comment.
