### ISSUE TITLE
Chart inside an BottomSheetScaffold pop the BottomSheet

### ISSUE THREAD

**Issue by GuillaumeEbert** [patrykandpatryk/vico#161]
Hello, 

I'm displaying a line chart in a BottomSheetScaffold. I specify to the BottomSheetScaffold that the BottomSheet must be collapsed, except that as soon as the graph is drawn the bottomsheet extends.

I need to explicitly tell the bottomSheetScaffoldState to collapse the bottomsheet after my chart is drawn.

When I use a surface with a height x the bottomsheet remains well collapsed

My Scaffold

```kotlin
val bottomSheetScaffoldState = rememberBottomSheetScaffoldState(
        bottomSheetState = rememberBottomSheetState(BottomSheetValue.Collapsed)
)

 BottomSheetScaffold(
        modifier = modifier,
        sheetContent = {
            Surface(modifier = Modifier.padding(MaterialTheme.padding.default.all)) {
                BalanceGraph(balanceChartProducer)

                 //adding this to make sur the bottomsheet remains well collaps at first 
                 coroutineScope.launch {
                    bottomSheetScaffoldState.bottomSheetState.collapse()
                }
            }

        },
        scaffoldState = bottomSheetScaffoldState,
```

My Graph

```kotlin

Chart(
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.fixed(
                minY = 500f,
                maxY = 758f
            ),
            lines = currentChartStyle.lineChart.lines.map {
                it.also { it.pointConnector = DefaultPointConnector(0f) }
            }
        ),
        chartScrollSpec = rememberChartScrollSpec(isScrollEnabled = false),
        chartModelProducer = producer,
        startAxis = startAxis(),
        bottomAxis = bottomAxis(
            valueFormatter = DecimalFormatAxisValueFormatter(
                decimalFormat = DecimalFormat(".###")
            )
        ),
        runInitialAnimation = false,
    )

```

I tested if runInitialAnimation was the cause of this unexpected opening. Unfortunately the behavior remains the same with the variable set to false

The state of my screen when I first display it
![image](https://user-images.githubusercontent.com/17883913/204107752-ef418466-84d5-43e3-b831-0ae12888d94e.png)

Thanks for your help or analysis.

Best regards

**Comment by patrykmichalik** [comment]
This looks to be a bug. Thanks for the report!

**Comment by patrykmichalik** [comment]
Hello! Vico 1.6.0, which is now rolling out, resolves the bug in question. Thank you for the report!
