### ISSUE TITLE
Is there a way to change the yAxis min and max values?

### ISSUE THREAD

**Issue by chungwwei** [patrykandpatryk/vico#171]
```
Chart (
    chart = lineChart(),
    chartModelProducer = producer,
    startAxis = startAxis(maxLabelCount = 5),
    bottomAxis = bottomAxis(),
)
```
<img width="254" alt="image" src="https://user-images.githubusercontent.com/39935368/208286226-75be1d3a-9b86-406a-aa9e-f58600a26e3f.png">

Is there support for a custom starting value and ending value in the y-axis? The default is doing its own spacing, so the chart looks like a straight line even thou the y-values are different. I like the y-axis to range from `min(yValues)` to `max(yValues)`.

TIA

Edit: whoops. I just need to need to set `maxY` and `minY` and that works, but its marked as`deprecated`

**Comment by patrickmichalik** [comment]
Hello! You can use a custom `AxisValuesOverrider` implementation for this purpose, passing it to the `lineChart` composable function as an argument. The parameter name is `axisValuesOverrider`. The `minY` and `maxY` parameters of the `Chart` composable function are deprecated in favor of this solution.
