### ISSUE TITLE
Screenshots in README

### ISSUE THREAD

**Issue by giovanniberti** [patrykandpatryk/vico#71]
Hi! First of all, thank you for the library! Could you please add some screenshots in the readme and/or in the wiki?

**Comment by giovanniberti** [comment]
Nothing major, I was thinking of:
 * Putting *"All of the charts included in the graphic at the top of this README are implemented in the sample app."* right below the charts at the top of the README (not gonna lie, they're so good I thought they were some kind of logo instead of actual charts produced by the library!)
 * Some more screenshots in the [wiki home](https://github.com/patrykandpatryk/vico/wiki/) and/or in the [charts types](https://github.com/patrykandpatryk/vico/wiki/Chart-types) section

**Comment by patrykmichalik** [comment]
Thanks for the suggestions! I’ve given the image in the README a caption mentioning that the charts shown in the image are implemented in the sample app, and I’ve added three pictures on the “Chart types” page of the wiki. Let me know what you think!

**Comment by giovanniberti** [comment]
Perfect! 🎉

**Comment by patrykmichalik** [comment]
Thanks again for the feedback!
