### ISSUE TITLE
Timeseries chart

### ISSUE THREAD

**Issue by michaelnimbs** [patrykandpatryk/vico#73]
Are there any plans to support timeseries charts and multiple axis?

The scenario is a temperature chart:
- timestamp values for the x axis
- humidity in % for the left y axis 
- temperature in Celsius for the right y axis

Thank you for the library!

**Comment by patrykmichalik** [comment]
Hello! It’s already possible to format the values displayed along chart axes, meaning that you can display dates, percentages, and so on. To do so, you can create an `AxisValueFormatter` implementation. However, you cannot yet configure the charts contained in a `ComposedChart` to be independently scaled, and consequently, it’s not possible to assign a specific axis to a given chart. I believe both of these things would be required for your use case. This is something that we’ll be looking into as soon as possible. Thank you for the suggestion!

**Comment by patrykmichalik** [comment]
Hello! Vico 1.0.0 Beta 1 enables you to configure the charts included in a `ComposedChart` to be independently scaled. You can connect a chart to a specific vertical axis via the `targetVerticalAxisPosition` parameter. We’re working on a new sample app and will include in it an example of this functionality. Vico 1.0.0 Beta 1 will be available within half an hour or so.
