### ISSUE TITLE
How to increase padding between the label and the bottom of the chart?

### ISSUE THREAD

**Issue by ArthurKun021** [patrykandpatryk/vico#77]
![image](https://user-images.githubusercontent.com/16458204/168042048-bec8a373-bf0e-40d6-b03d-05ae935c32db.png)

I used a custom axis label but can't managed to show all of the label.

Is there any way to give space to it?

**Comment by patrykmichalik** [comment]
Hello! If the appropriate `SizeConstraint` is used, this should happen automatically. However, it would appear that thereʼs a bug in `TextComponent` that may cause the text to be unduly truncated. Thanks for bringing this to our attention. Weʼll be looking into it as soon as possible.

**Comment by patrykmichalik** [comment]
Hello! Vico 1.0.0 Beta 1 resolves the bug in question. The update will be available within half an hour or so.
