### ISSUE TITLE
As listener showing marker?

### ISSUE THREAD

**Issue by SuleymanovTat** [patrykandpatryk/vico#94]
As listener showing marker?

**Comment by patrykmichalik** [comment]
Hello! Unfortunately, I’m not sure I understand. Would you be able to expand on that?

**Comment by SuleymanovTat** [comment]
<img width="98" alt="Снимок экрана 2022-06-14 в 10 06 02" src="https://user-images.githubusercontent.com/8472653/173514976-b7a1cd67-95f2-4d53-9871-371dfc52faf5.png">
the user clicks on the chart, the chart shows a marker, I need to listen to this

**Comment by patrykmichalik** [comment]
Got it! Pull request #96 will add such functionality. The feature will be available in the next release of Vico.

**Comment by patrykmichalik** [comment]
Hello! Vico 1.2.0 introduces the feature requested. The update should be available within 30 minutes. Thanks for the suggestion!
