### ISSUE TITLE
how to indicate the amount on the x-axis in the chart, for example 6?

### ISSUE THREAD

**Issue by SuleymanovTat** [patrykandpatryk/vico#95]
Thanks for the library
How to indicate the amount on the x-axis in the chart, for example 6? <img width="332" alt="Снимок экрана 2022-06-16 в 09 08 27" src="https://user-images.githubusercontent.com/8472653/174003764-483c54aa-c101-4058-8f13-cf868276c4f0.png">

**Comment by SuleymanovTat** [comment]
i need maxLabelCount for Horizontal, how can i do that?

**Comment by Gowsky** [comment]
Hello! I’m sorry, but it’s not supported currently, but we will add this option soon.
